Repository nanoframework/System.Net.Http, pull requests merged in 2021-03, with the labels that each got.

#175 Remove Console.WriteLine as no longer supported.
  nanoFramework.System.Net.Http/Http/System.Net.HttpListener.cs
  nanoFramework.System.Net.Http/Http/System.Net._InputNetworkStreamWrapper.cs
Labels: Type: bug

#178 Add constants with schema to Uri
  nanoFramework.System.Net.Http/Http/System.Net.HttpListener.cs
  nanoFramework.System.Net.Http/Http/System.Net.HttpWebRequest.cs
  nanoFramework.System.Net.Http/Http/System.Uri.cs
Labels: Type: enhancement

#179 Add support for WebSockets
  nanoFramework.System.Net.Http/Friends.cs
  nanoFramework.System.Net.Http/Http/System.Net.HttpListener.cs
  nanoFramework.System.Net.Http/Http/System.Net.HttpWebRequest.cs
  nanoFramework.System.Net.Http/Http/System.Net.Internal.cs
  nanoFramework.System.Net.Http/Http/System.Net.WebHeaders.cs
  nanoFramework.System.Net.Http/Http/System.Net.WebRequest.cs
  nanoFramework.System.Net.Http/Http/System.Uri.cs
  nanoFramework.System.Net.Http/System.Net.Http.nfproj
  version.json
Labels: Type: enhancement

#180 Add missing header information for websockets headers
  nanoFramework.System.Net.Http/Http/System.Net._HeaderInfoTable.cs
Labels: Type: enhancement

#181 Improve Host HTTP header
  nanoFramework.System.Net.Http/Http/System.Net.HttpWebRequest.cs
Labels: Breaking-Change
