Repository nanoframework/System.Net.Http, pull requests merged in 2022-01, with the labels that each got.

#263 Add WebSocketContext class
  nanoFramework.System.Net.Http.Server/System.Net.Http.Server.nfproj
  nanoFramework.System.Net.Http/Http/System.Net.HttpListenerContext.cs
  nanoFramework.System.Net.Http/Http/System.Net.HttpListenerResponse.cs
  nanoFramework.System.Net.Http/Http/System.Net.WebSocketContext.cs
  nanoFramework.System.Net.Http/System.Net.Http.nfproj
  version.json
Labels: Type: enhancement

#264 Fix declaration for WebSockets assembly
  nanoFramework.System.Net.Http/Friends.cs
Labels: Type: bug

#266 Fix Close in HttpListenerContext
  nanoFramework.System.Net.Http/Http/System.Net.HttpListenerContext.cs
Labels: Type: bug, Breaking-Change
